### ISSUE TITLE
kea-admin / admin-utils.sh ignores the -h --host arg for the database

### ISSUE THREAD

**Issue by Kroki0815** [isc-projects/kea#104]
If the mysql-database is not on localhost, upgrade of the database with kea-admin is not possible.

i looked into the code and the problem is in the admin-utils.sh:

>mysql_execute() {
    QUERY=$1
    shift
    if [ $# -gt 1 ]; then
        mysql -N -B "$@" -e "${QUERY}"
        retcode=$?
    else
        mysql -N -B --database="${db_name}" --user="${db_user}" --password="${db_password}" -e "${QUERY}"
        retcode=$?
    fi
    return $retcode
}

>mysql_execute_script() {
    file=$1
    shift
    if [ $# -ge 1 ]; then
        mysql -N -B "$@" < "${file}"
        retcode=$?
    else
        mysql -N -B --database="${db_name}" --user="${db_user}" --password="${db_password}" < "${file}"
        retcode=$?
    fi
    return $retcode
}

The mysql lines should look like this:

>mysql -N -B **--host="${db_host}"** --database="${db_name}" --user="${db_user}" --password="${db_password}"

This problem may be also in the other backends.

This bug is in all versions, also in the master-branch.

**Comment by vrisk** [comment]
Thank you for making this bug report. I am sorry we  have not replied sooner. I have just migrated the issue to our current issue tracker at https://gitlab.isc.org/isc-projects/kea/issues/319. Please look there for any comments or to add more information. 
Again, very sorry for neglecting to respond sooner. We are consolidating to a single issue tracker because it is just too hard to monitor more than one.
