### ISSUE TITLE
Questions about Kea HA.

### ISSUE THREAD

**Issue by cold01water** [isc-projects/kea#105]
##  2 nodes "partner down" state

https://kea.isc.org/wiki/ HADesign has the following statement.

>  If the two servers can't communicate with each because of the control channel failure (network partition) the servers are unable to send lease updates to each other. However, both servers may be still responding to the DHCP requests sent to them. Normally, the server waits with a response to the client until it gets an acknowledgement to a lease update. If the network is partitioned the lease updates can't be delivered. In such case, the servers must respond to the DHCP clients despite not delivering lease updates to the peers. If the servers were dropping the DHCP requests because the network partition, it would lead to the increased number of the rebinding requests from the DHCP clients. As a consequence, both servers would transition to the partner down state. 

If two nodes go down, will they start responding from each other's pool? As a result, duplicate IP addresses will occur?

##  Can I control IP address duplication at the DB backend?

I believe that duplication of IP addresses can be controlled by using the same lease DB on two nodes. Is this idea correct?

**Comment by vrisk** [comment]
col01water - yes. if two Kea servers try to hand out the same IP address from the same lease database backend, one of the Kea servers (whichever tries to write the lease first) will 'win' and the other will have to retry with another address. So, even if the two Kea servers cannot communicate with each other, if they have a shared backend, they won't duplicate addresses. It is kind of hard to imagine that they would each have connectivity to the shared lease db and not have connectivity with each other, however, so maybe I am misinterpreting the question. 

We are closing this issue tracker because we are using https://gitlab.isc.org/isc-projects/kea as our main repo.  If you have a bug report to submit, please enter it there instead of here.

If you have followup questions, could you post them on kea-users@lists.isc.org?  Thank you!
