### ISSUE TITLE
Bug in hostname encoding in lease.

### ISSUE THREAD

**Issue by max197616** [isc-projects/kea#110]
**Describe the bug**
When trying to execute a command 'lease4-get-all', I get an error:
`./kea-shell --port 8080 --service dhcp4 lease4-get-all
[ { "result": 1, "text": "internal server error: unable to parse server's answer to the forwarded message: Bad escape in <wire>:0:33939" } ]`

**To Reproduce**
1. Run Kea dhcpv4 with lease memfile database.
2. Wait for some time, while all clients obtain IP.
3. Try to get all leases through the kea-shell.

**Expected behavior**

**Environment:**
 - Kea version: 
1.4.0
tarball
linked with:
log4cplus 1.1.3
OpenSSL 1.0.1t  3 May 2016
database:
MySQL backend 6.0, library 5.5.59
Memfile backend 2.0

 - OS: Debian 7
 - Hooks:
lease_cmds
stat_cmds

I think that somewhere there is a problem in encoding hostname in lease.

**Comment by max197616** [comment]
I think I've found the problem. Need to modify [line](https://github.com/isc-projects/kea/blob/master/src/lib/cc/data.cc#L800)  to
`if (((c >= 0) && (c < 0x20)) || (c >= 7f && c <= 0xff ) {`

**Comment by fxdupont** [comment]
BTW what is the hostname?

Regards

Francis Dupont <fdupont@isc.org>

**Comment by max197616** [comment]
I've found following hostnames in the lease file:
\171\165\173\160.
user-\143\138.
\128\164\172\168\173-\143\138.
and many others like these.

**Comment by fxdupont** [comment]
if (((c >= 0) && (c < 0x20)) || (c < 0) || (c >= 0x7f)) {

works better. Note that fromJSON is not enable to re-read this
(known problem fixed in gitlab #45 !40 which unfortunately won't be in 1.5
according to the current schedule. Of course the line above was cut &
paste from this branch).

Regards

Francis Dupont <fdupont@isc.org>

PS: the hostname allowed char set is a very limited subset of ASCII
so in theory you should not have this kind of problems with hostnames.
PPS: 0x7f is a legal character in ECMA 404 but I agree to escape it!
PPPS: your message
> I think I've found the problem. Need to modify [line](https://github.com/isc-
> projects/kea/blob/master/src/lib/cc/data.cc#L800)  to
> `if (((c >= 0) && (c < 0x20)) || (c >= 7f && c <= 0xff ) {`

**Comment by max197616** [comment]
Yes, I made a change and there is no more error.
Thanks.
