### ISSUE TITLE
Warning message "the interface x is down" is incomplete.

### ISSUE THREAD

**Issue by brubbel** [isc-projects/kea#95]
(Note: This was tested on Kea 1.1.0, but I see that this issue is still present in the latest 1.4.0 version.)
At startup, Kea may produce the following warning message:
`DHCPSRV_OPEN_SOCKET_FAIL failed to open socket: the interface x is down or has no usable IPv4 addresses configured`

I checked interface x of course, but it was [UP] and had an IPv4 address assigned.
It turns out (from reading the source) that Kea expects interface x also being in the [RUNNING] state.

I suggest to change [the warning message](https://github.com/isc-projects/kea/blob/2147c6a3409c0974a6e2996e8f8a7c1c5fc877c7/src/lib/dhcp/iface_mgr.cc#L480-L485) into "has no usable IPv4 address or is missing flags [UP] and/or [RUNNING]."

As a related question: why does isc-dhcp allow and kea-dhcp does not allow starting a server on an interface without the IFF_RUNNING flag set? 
In any case, kea 1.1.0 does not work when the interface is not [RUNNING] when it was started, even when it becomes [RUNNING] afterwards. When the state goes from running->not running->running: all ok.

**Comment by vrisk** [comment]
Hello brubbel - I am sorry we have replied to your issue report yet. I have migrated it to our current issue tracker at https://gitlab.isc.org/isc-projects/kea/issues/323.  Please go there for any updates. Thank you for the detail provided here, it looks actionable to me. (even if only with a doc comment, if this is intentional behavior)
